### ISSUE TITLE
Please add regex support

### ISSUE THREAD

**Issue by alexolog** [MichelePezza/CopyLinksplusplus#1]
Filtering by regex is more useful and flexible than filtering by a list of domain names.

**Comment by MichelePezza** [comment]
In my code I use regex to filter. Regex are too complex for a common users this is the reason I decided for a domains list that an user can easily insert.
I'm considering to  add a regex feature as enanchment.

**Comment by MichelePezza** [comment]
Adde regex support! Thanks for the suggestion.

**Comment by alexolog** [comment]
Great!
