### ISSUE TITLE
[Request] copia.... e incolla?

### ISSUE THREAD

**Issue by gabri25ele** [MichelePezza/CopyLinksplusplus#2]
Oltre alla copia, c'è la possibilità di implementare il contrario? 
Ovvero incollare e aprire un elenco di link, tutti insieme?

**Comment by MichelePezza** [comment]
Non ho capito la domanda?
Cosa intendi?

**Comment by gabri25ele** [comment]
tipo quello che fa questa estensione:
https://github.com/htrinter/Open-Multiple-URLs

**Comment by MichelePezza** [comment]
Ora comprendo!
La funzionalità che descrivi è uno sviluppo completamente nuovo alla quale al momento non sono interessato.
L'idea principale per cui ho sviluppato l'addon è quello di catturare specifici link negli appunti in modo che un downloader esterno a firefox li possa catturare e gestirne il download.

Ti ringrazio comunque per il suggerimento

**Comment by gabri25ele** [comment]
ah ok
chiedevo in caso si potesse implementare facilmente... sarebbe stato utile almeno per me avere sia il copia che l'incolla.
fa niente, come non detto.
