### ISSUE TITLE
Copy current Window problem!

### ISSUE THREAD

**Issue by HAMiDY25** [MichelePezza/CopyLinksplusplus#5]
Copy current window doesn't work. 👾
Current Tab works fine.
Please fix it.
Thanks 🌹
Win10 FF80 x64

**Comment by MichelePezza** [comment]
I made a fresh install Win10 FF80 x64 with  Copylinks++....
... i don't get any errors... it works without issues. (the only extension installed is copylink++)
Could you please help to understand your case with further information?
Could you try to install only copylinks++ in a new profile?

Thx 
M

**Comment by HAMiDY25** [comment]
In a new profile at first its worked but after restart FF, no! 🤨
But I found the problem. If any Mozilla internal page tab is open, the issue occurs.
Like about:profiles or chrome://global/content/config.xhtml

**Comment by MichelePezza** [comment]
Yes you found it. I will fix the addon soon.

Thanks 
MP
