### ISSUE TITLE
Please make the duplicate filter & sorting optional

### ISSUE THREAD

**Issue by muzuc** [MichelePezza/CopyLinksplusplus#6]
Hello,

i love your add-on but i would love it even more if it could be optional to sort and remove duplicates. The fact is i'm interested in the right order of the links and also the duplicates. By the way it's really useful to extract all the links in a window and even in all the windows depending on how we're organized. So thank you for your precious work

**Comment by MichelePezza** [comment]
Release 2.3.0 has now a setting to enable/disable "remove duplicates and sorting"

Ciao
MP
