### ISSUE TITLE
Source for Copy All Tab Urls?

### ISSUE THREAD

**Issue by ocdtrekkie** [MichelePezza/CopyLinksplusplus#7]
Hello,

We are reviewing some extensions and were looking for the source for the "Copy All Tab Urls" extension which you also maintain. It is listed as being licensed under MPLv2, but I cannot find the source code.

https://addons.mozilla.org/en-US/firefox/addon/copy-all-tab-urls-we/

**Comment by MichelePezza** [comment]
You can get the source code of every addon by unzipping the file .xpi.

About "Copy All Tab Urls" the code is posted here now. 

Ciao
MP

**Comment by ocdtrekkie** [comment]
Learn something new every day. Thanks!
